name: Java CI with Maven - Test and Package
on: [pull_request]
    
jobs:
  build:
    name: Build and Test Java Project
    runs-on: ubuntu-latest

    steps:
      # Etape 1
      - name: Checkout repository
        uses: actions/checkout@v4
      # Etape 2
      - name: Set up repository
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '21'
      # Etape 3
      - name: Create my package
        run: mvn -B package --file pom.xml
